### ISSUE TITLE
PROPOSAL: Support for multiple images/paths

### ISSUE THREAD

**Issue by jpcoles** [eth-cscs/slurm-uenv-mount#31]
### Proposal

As discussed at the 23q2 QPM, we will need support for mounting multiple images. The proposed interface was a comma-separated list of file/mount-point pairs:

`--uenv=<file>[:mount-point][,<file:mount-point>]*
`

The default mount point for the first file would be "/user-environment" but subsequent files require a user to specify a location. No two mount points can be the same. A possible variation could be to allow the default mount point to appear anywhere in the list provided all other files are paired with an explicit mount point (however, see comments on duplicates below).

Furthermore, one could instead use

`--uenv-file=images.yaml`

where the YAML file would contain the description of files/mount-points to use.

### Examples

- `--uenv=compilers.sqfs`
   compilers.sqfs mounted under /user-environment
- `--uenv=compilers.sqfs:/home/username/mycompilers`
   compilers.sqfs mounted under /home/username/mycompilers
- `--uenv=compilers.sqfs,debuggers:/home/username/mydebuggers`
  compilers.sqfs mounted under /user-environment
  debuggers mounted under /home/username/mydebuggers
- `--uenv=compilers.sqfs:/home/username/mycompilers,debuggers:/home/username/mydebuggers`
  compilers.sqfs mounted under /home/username/mycompilers
  debuggers mounted under /home/username/mydebuggers
  /user-environment empty
- `--uenv=compilers.sqfs:/home/username/mycompilers,myapps.sqfs`
   compilers.sqfs mounted under /home/username/mycompilers
  myapps.sqfs mounted under /user-environment

### Environment Variables

Instead of using UENV_FILE and UENV_MOUNT we have a single UENV_IMAGES that maintains a union of all active image/mount-point pairs.

### Comment on Duplicate Mount points

Since we already allow an `srun` command to override the active uenv, one could argue it is consistent to allow duplicate mount points where the last mount point takes precedence. (Internally we populate a hash table of (mount-point,file) key-value pairs that is initialized to the current values in $UENV_IMAGES).

### Protocol Extensions

A further extension could support images stored on a remote server through a protocol tag

`--uenv=[protocol]file[:mount-point][,[protocol]file[:mount-point]]*
`

The default protocol would be "file://" if left unspecified, but might support "http://", "jfrog://", or something custom like "cscs://".

**Comment by bcumming** [comment]
This was implemented
